namespace: locust
resources:
- namespace.yaml
- master-deploy.yaml
- master-svc.yaml
- worker-deploy.yaml
configMapGenerator:
- name: locust-target-host
  literals:
    - TARGET_HOST=https://example.com
- name: locust-tasks
  files:
    - tasks/tasks.py
