apiVersion: v1
kind: Service
metadata:
  name: locust-master
  labels:
    app: locust
    role: master
spec:
  type: NodePort
  ports:
  - name: master-web
    port: 8089
    targetPort: 8089
    nodePort: 0
    protocol: TCP
  - name: master-p1
    port: 5557
    protocol: TCP
    targetPort: 5557
  - name: master-p2
    port: 5558
    protocol: TCP
    targetPort: 5558
  selector:
    app: locust
    role: master
