apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-master
  labels:
    app: locust
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: master
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      containers:
      - name: locust
        image: quay.io/honestbee/locust:0.7.5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        envFrom:
        - configMapRef:
            name: locust-target-host
        env:
        - name: LOCUST_MODE
          value: master
        - name: LOCUST_SCRIPT
          value: /locust-tasks/tasks.py
        ports:
        - containerPort: 8089
          name: loc-master-web
          protocol: TCP
        - containerPort: 5557
          name: loc-master-p1
          protocol: TCP
        - containerPort: 5558
          name: loc-master-p2
          protocol: TCP
        volumeMounts:
          - name: locust-tasks
            mountPath: /locust-tasks/
        livenessProbe:
          periodSeconds: 30
          httpGet:
            path: /
            port: 8089
        readinessProbe:
          periodSeconds: 30
          httpGet:
            path: /
            port: 8089
      volumes:
      - name: locust-tasks
        configMap:
          name: locust-tasks
