apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    app: locust
    role: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: locust
      role: worker
  template:
    metadata:
      labels:
        app: locust
        role: worker
    spec:
      containers:
      - name: locust
        image: quay.io/honestbee/locust:0.7.5
        volumeMounts:
          - name: locust-tasks
            mountPath: /locust-tasks/
        envFrom:
        - configMapRef:
            name: locust-target-host
        env:
        - name: LOCUST_MODE
          value: worker
        - name: LOCUST_MASTER
          value: locust-master
        - name: LOCUST_MASTER_WEB
          value: "8089"
        - name: LOCUST_SCRIPT
          value: /locust-tasks/tasks.py
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
        - name: locust-tasks
          configMap:
            name: locust-tasks
